# Generated by Django 2.1 on 2018-08-25 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('titre', models.CharField(max_length=150)),
                ('auteur', models.CharField(max_length=150)),
                ('editeur', models.CharField(max_length=150)),
                ('etat', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('vote', models.IntegerField()),
                ('image', models.FileField(upload_to='images/liv/')),
                ('categorie', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('date_parution', models.DateTimeField()),
                ('resume', models.TextField()),
                ('sommaire', models.TextField()),
                ('point_vente', models.IntegerField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
