# Generated by Django 2.1 on 2018-08-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0002_auto_20180825_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
