# Generated by Django 2.1 on 2018-08-31 07:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0006_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='sommaire',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
