# Generated by Django 2.1 on 2018-09-01 03:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0007_auto_20180831_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
