# Generated by Django 2.1 on 2018-09-01 03:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0008_auto_20180901_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
