# Generated by Django 2.1 on 2018-09-01 03:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0009_auto_20180901_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='caracteristique',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livre',
            name='sommaire',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
