# Generated by Django 2.1 on 2018-09-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0010_auto_20180901_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
