# Generated by Django 2.1 on 2018-09-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0012_auto_20180910_1831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='infos',
            name='category',
        ),
        migrations.AlterField(
            model_name='infos',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
