# Generated by Django 2.1 on 2018-09-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0013_auto_20180910_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='slug',
            field=models.SlugField(default='abc'),
        ),
    ]
