# Generated by Django 2.1 on 2018-09-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0014_auto_20180910_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos',
            name='slug',
        ),
    ]
