# Generated by Django 2.1 on 2018-09-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0015_remove_infos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='slug',
            field=models.SlugField(default=True),
        ),
    ]
