# Generated by Django 2.1 on 2018-09-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0017_auto_20180910_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infos',
            old_name='date_ajout',
            new_name='date_aj',
        ),
    ]
