# Generated by Django 2.1 on 2018-09-11 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0018_auto_20180911_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos',
            name='date_aj',
        ),
        migrations.AddField(
            model_name='infos',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
