# Generated by Django 2.1 on 2018-09-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upluss', '0019_auto_20180911_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='slug',
            field=models.SlugField(blank=True, default='abc'),
            preserve_default=False,
        ),
    ]
